// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWHsOKDUpaxff9PpERiLnvYZtww-8J6mk',
    appId: '1:991042230435:web:f842267613f9a531fb0716',
    messagingSenderId: '991042230435',
    projectId: 'matakuliah-8f458',
    authDomain: 'matakuliah-8f458.firebaseapp.com',
    storageBucket: 'matakuliah-8f458.appspot.com',
    measurementId: 'G-43M1WCML8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCkXBnbuKp4QeMDcusLuaJq4S5hMcLfTg',
    appId: '1:991042230435:android:321100c2a3584197fb0716',
    messagingSenderId: '991042230435',
    projectId: 'matakuliah-8f458',
    storageBucket: 'matakuliah-8f458.appspot.com',
  );
}
